### ISSUE TITLE
请检查发布版本

### ISSUE THREAD

**Issue by 88250** [muhanstudio/siyuan-widget-Color-Calendar#1]
集市构建报错：

![image](https://github.com/muhanstudio/siyuan-widget-Color-Calendar/assets/873584/5b60b36f-27bc-4af0-a028-cf20a2845424)

用户端也有反馈：

https://github.com/siyuan-note/siyuan/issues/10035

麻烦抽空检查并发布新版本，谢谢。

**Comment by muhanstudio** [comment]
收到，会跟进修改后重新发布

**Comment by 88250** [comment]
你好，麻烦处理一下，否则日志中报错太多，谢谢。

**Comment by muhanstudio** [comment]
> 你好，麻烦处理一下，否则日志中报错太多，谢谢。

不好意思，已经修改完发布了
https://github.com/muhanstudio/siyuan-widget-Color-Calendar/tree/0.0.3

**Comment by 88250** [comment]
你好，现在打开挂件集市会导致大量报错 https://ld246.com/article/1705405119690 

我们暂时先下架该插件，麻烦后面解决以后重新 PR，辛苦了。

**Comment by muhanstudio** [comment]
好的没问题D大
